### ISSUE TITLE
Error initializing scanner: No valid license found

### ISSUE THREAD

**Issue by cuckoo-linux** [NextronSystems/spark-core#5]
root@test:/home/test/Desktop/spark-core-linux-pack# ./spark-core-linux-x64

                                                                               
       _______  ___   ___  __ __  _________  ___  ____                         
      / __/ _ \/ _ | / _ \/ //_/ / ___/ __ \/ _ \/ __/                         
     _\ \/ ___/ __ |/ , _/ ,<   / /__/ /_/ / , _/ _/                           
    /___/_/  /_/ |_/_/|_/_/|_|  \___/\____/_/|_/___/                           
                                                                               
   Fast IOC and YARA Scanner                                                   
   Copyright by Nextron Systems GmbH, 2018                                     
   v1.14.12                                                                    

Scan Info                                                                      
Info Init SPARK Core Version: 1.14.12
Info Init Run on system: test
Info Init Running as user: root
Info Init Argument list: [./spark-core-linux-x64]
Info Init Platform: linux  (Linux test 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux  )
Info Init CPU Count: 4
Info Init Writing report file to: test_spark_2018-08-06.log
Info Init Syslog export: disabled
Info Init Scanning system drive only
Info Init IP Address 1: 192.168.1.58
Info Init Maximum runtime in hours: 72
Info Init Reading assets from working directory /home/test/Desktop/spark-core-linux-pack
Info Init Get a free SPARK Core license https://www.nextron-systems.com/spark-core/
**Error Init Error initializing scanner: No valid license found**

**Comment by Neo23x0** [comment]
Did you drop the license in the folder?

**Comment by Codehardt** [comment]
You should've received a SPARK Core License via mail during subscription process as attachment.

**Comment by cuckoo-linux** [comment]
i received this email:
Thank you for your interest in SPARK Core and the newsletter subscription.
Please find attached a license for SPARK Core and the download links below.

Download SPARK Core for Windows: https://update1.nextron-systems.com/getcore.php?type=sparkcorewin
Download SPARK Core for Linux: https://update1.nextron-systems.com/getcore.php?type=sparkcorelinux
Download SPARK Core for mac OS: https://update1.nextron-systems.com/getcore.php?type=sparkcoreosx

Please report errors via https://github.com/NextronSystems/spark-core/issues
Please report false positives via https://github.com/Neo23x0/signature-base/issues

**Comment by cuckoo-linux** [comment]
there is no license in attachment:(

**Comment by cuckoo-linux** [comment]
when i can it on windows even in administrator mode access was denied.couldnt able to run both in windows and linux.

**Comment by cuckoo-linux** [comment]
now i have subscribed using my yahoo account, but haven't got files yet.As soon as i will receive files, will test and update status.:)

**Comment by cuckoo-linux** [comment]
it is running successfully now:).thanks everyone for help.
